services:
  minio:
    image: minio/minio:latest
    container_name: lqr-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  create-bucket:
    image: minio/mc:latest
    container_name: lqr-create-bucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb -p local/data-lake || true;
      mc anonymous set none local/data-lake;
      exit 0;
      "

  kafka:
    image: apache/kafka:4.1.2
    container_name: lqr-kafka
    ports:
      - "9092:9092"

volumes:
  minio_data: